// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: shard.proto

package shardpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardMaster_Join_FullMethodName  = "/shard.ShardMaster/Join"
	ShardMaster_Leave_FullMethodName = "/shard.ShardMaster/Leave"
	ShardMaster_Move_FullMethodName  = "/shard.ShardMaster/Move"
	ShardMaster_Query_FullMethodName = "/shard.ShardMaster/Query"
)

// ShardMasterClient is the client API for ShardMaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义 ShardMaster 中控节点提供的 RPC 服务
type ShardMasterClient interface {
	Join(ctx context.Context, in *JoinArgs, opts ...grpc.CallOption) (*JoinReply, error)
	Leave(ctx context.Context, in *LeaveArgs, opts ...grpc.CallOption) (*LeaveReply, error)
	Move(ctx context.Context, in *MoveArgs, opts ...grpc.CallOption) (*MoveReply, error)
	Query(ctx context.Context, in *QueryArgs, opts ...grpc.CallOption) (*QueryReply, error)
}

type shardMasterClient struct {
	cc grpc.ClientConnInterface
}

func NewShardMasterClient(cc grpc.ClientConnInterface) ShardMasterClient {
	return &shardMasterClient{cc}
}

func (c *shardMasterClient) Join(ctx context.Context, in *JoinArgs, opts ...grpc.CallOption) (*JoinReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, ShardMaster_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardMasterClient) Leave(ctx context.Context, in *LeaveArgs, opts ...grpc.CallOption) (*LeaveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveReply)
	err := c.cc.Invoke(ctx, ShardMaster_Leave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardMasterClient) Move(ctx context.Context, in *MoveArgs, opts ...grpc.CallOption) (*MoveReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveReply)
	err := c.cc.Invoke(ctx, ShardMaster_Move_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardMasterClient) Query(ctx context.Context, in *QueryArgs, opts ...grpc.CallOption) (*QueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReply)
	err := c.cc.Invoke(ctx, ShardMaster_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardMasterServer is the server API for ShardMaster service.
// All implementations must embed UnimplementedShardMasterServer
// for forward compatibility.
//
// 定义 ShardMaster 中控节点提供的 RPC 服务
type ShardMasterServer interface {
	Join(context.Context, *JoinArgs) (*JoinReply, error)
	Leave(context.Context, *LeaveArgs) (*LeaveReply, error)
	Move(context.Context, *MoveArgs) (*MoveReply, error)
	Query(context.Context, *QueryArgs) (*QueryReply, error)
	mustEmbedUnimplementedShardMasterServer()
}

// UnimplementedShardMasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardMasterServer struct{}

func (UnimplementedShardMasterServer) Join(context.Context, *JoinArgs) (*JoinReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedShardMasterServer) Leave(context.Context, *LeaveArgs) (*LeaveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Leave not implemented")
}
func (UnimplementedShardMasterServer) Move(context.Context, *MoveArgs) (*MoveReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedShardMasterServer) Query(context.Context, *QueryArgs) (*QueryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedShardMasterServer) mustEmbedUnimplementedShardMasterServer() {}
func (UnimplementedShardMasterServer) testEmbeddedByValue()                     {}

// UnsafeShardMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardMasterServer will
// result in compilation errors.
type UnsafeShardMasterServer interface {
	mustEmbedUnimplementedShardMasterServer()
}

func RegisterShardMasterServer(s grpc.ServiceRegistrar, srv ShardMasterServer) {
	// If the following call panics, it indicates UnimplementedShardMasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardMaster_ServiceDesc, srv)
}

func _ShardMaster_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardMasterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardMaster_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardMasterServer).Join(ctx, req.(*JoinArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardMaster_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardMasterServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardMaster_Leave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardMasterServer).Leave(ctx, req.(*LeaveArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardMaster_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardMasterServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardMaster_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardMasterServer).Move(ctx, req.(*MoveArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardMaster_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardMasterServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardMaster_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardMasterServer).Query(ctx, req.(*QueryArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardMaster_ServiceDesc is the grpc.ServiceDesc for ShardMaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardMaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shard.ShardMaster",
	HandlerType: (*ShardMasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _ShardMaster_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _ShardMaster_Leave_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _ShardMaster_Move_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _ShardMaster_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shard.proto",
}
