// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: shard.proto

package shardpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Num           int64                   `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`                                                                                  // 配置版本号 (严格单调递增，比如 1, 2, 3...)
	Shards        map[int64]int64         `protobuf:"bytes,2,rep,name=Shards,proto3" json:"Shards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 分片映射表：ShardID (固定 0-9) -> GroupID
	Groups        map[int64]*GroupServers `protobuf:"bytes,3,rep,name=Groups,proto3" json:"Groups,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`  // GroupID -> 该 Group 下的所有服务器地址列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Config) GetShards() map[int64]int64 {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *Config) GetGroups() map[int64]*GroupServers {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupServers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []string               `protobuf:"bytes,1,rep,name=Servers,proto3" json:"Servers,omitempty"` // 物理节点的 RPC 地址，例如 ["127.0.0.1:8001", "127.0.0.1:8002"]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupServers) Reset() {
	*x = GroupServers{}
	mi := &file_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupServers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupServers) ProtoMessage() {}

func (x *GroupServers) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupServers.ProtoReflect.Descriptor instead.
func (*GroupServers) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{1}
}

func (x *GroupServers) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type JoinArgs struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Servers       map[int64]*GroupServers `protobuf:"bytes,1,rep,name=Servers,proto3" json:"Servers,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 新增的 GroupID -> 服务器列表
	ClientId      int64                   `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`                                                                         // 用于复用你写好的防重放机制
	SeqId         int64                   `protobuf:"varint,3,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinArgs) Reset() {
	*x = JoinArgs{}
	mi := &file_shard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinArgs) ProtoMessage() {}

func (x *JoinArgs) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinArgs.ProtoReflect.Descriptor instead.
func (*JoinArgs) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{2}
}

func (x *JoinArgs) GetServers() map[int64]*GroupServers {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *JoinArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *JoinArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type JoinReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrongLeader   bool                   `protobuf:"varint,1,opt,name=WrongLeader,proto3" json:"WrongLeader,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinReply) Reset() {
	*x = JoinReply{}
	mi := &file_shard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinReply) ProtoMessage() {}

func (x *JoinReply) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinReply.ProtoReflect.Descriptor instead.
func (*JoinReply) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{3}
}

func (x *JoinReply) GetWrongLeader() bool {
	if x != nil {
		return x.WrongLeader
	}
	return false
}

func (x *JoinReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type LeaveArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GIDs          []int64                `protobuf:"varint,1,rep,packed,name=GIDs,proto3" json:"GIDs,omitempty"` // 要踢掉的 GroupID 列表
	ClientId      int64                  `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,3,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveArgs) Reset() {
	*x = LeaveArgs{}
	mi := &file_shard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveArgs) ProtoMessage() {}

func (x *LeaveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveArgs.ProtoReflect.Descriptor instead.
func (*LeaveArgs) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{4}
}

func (x *LeaveArgs) GetGIDs() []int64 {
	if x != nil {
		return x.GIDs
	}
	return nil
}

func (x *LeaveArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *LeaveArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type LeaveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrongLeader   bool                   `protobuf:"varint,1,opt,name=WrongLeader,proto3" json:"WrongLeader,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveReply) Reset() {
	*x = LeaveReply{}
	mi := &file_shard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveReply) ProtoMessage() {}

func (x *LeaveReply) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveReply.ProtoReflect.Descriptor instead.
func (*LeaveReply) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{5}
}

func (x *LeaveReply) GetWrongLeader() bool {
	if x != nil {
		return x.WrongLeader
	}
	return false
}

func (x *LeaveReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// ---------------------------------------------------------
// 3. Move: 管理员操作 - 强制把某个 Shard 分配给特定的 Group
// ---------------------------------------------------------
type MoveArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         int64                  `protobuf:"varint,1,opt,name=Shard,proto3" json:"Shard,omitempty"` // 分片 ID
	GID           int64                  `protobuf:"varint,2,opt,name=GID,proto3" json:"GID,omitempty"`     // 目标 GroupID
	ClientId      int64                  `protobuf:"varint,3,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,4,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveArgs) Reset() {
	*x = MoveArgs{}
	mi := &file_shard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveArgs) ProtoMessage() {}

func (x *MoveArgs) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveArgs.ProtoReflect.Descriptor instead.
func (*MoveArgs) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{6}
}

func (x *MoveArgs) GetShard() int64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *MoveArgs) GetGID() int64 {
	if x != nil {
		return x.GID
	}
	return 0
}

func (x *MoveArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *MoveArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type MoveReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrongLeader   bool                   `protobuf:"varint,1,opt,name=WrongLeader,proto3" json:"WrongLeader,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveReply) Reset() {
	*x = MoveReply{}
	mi := &file_shard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveReply) ProtoMessage() {}

func (x *MoveReply) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveReply.ProtoReflect.Descriptor instead.
func (*MoveReply) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{7}
}

func (x *MoveReply) GetWrongLeader() bool {
	if x != nil {
		return x.WrongLeader
	}
	return false
}

func (x *MoveReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

// ---------------------------------------------------------
// 4. Query: 客户端/数据节点操作 - 查询路由配置
// ---------------------------------------------------------
type QueryArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int64                  `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"` // 想要查询的版本号。如果是 -1，代表查询最新版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryArgs) Reset() {
	*x = QueryArgs{}
	mi := &file_shard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryArgs) ProtoMessage() {}

func (x *QueryArgs) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryArgs.ProtoReflect.Descriptor instead.
func (*QueryArgs) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{8}
}

func (x *QueryArgs) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type QueryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WrongLeader   bool                   `protobuf:"varint,1,opt,name=WrongLeader,proto3" json:"WrongLeader,omitempty"`
	Err           string                 `protobuf:"bytes,2,opt,name=Err,proto3" json:"Err,omitempty"`
	Config        *Config                `protobuf:"bytes,3,opt,name=Config,proto3" json:"Config,omitempty"` // 返回对应的路由表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReply) Reset() {
	*x = QueryReply{}
	mi := &file_shard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReply) ProtoMessage() {}

func (x *QueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReply.ProtoReflect.Descriptor instead.
func (*QueryReply) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{9}
}

func (x *QueryReply) GetWrongLeader() bool {
	if x != nil {
		return x.WrongLeader
	}
	return false
}

func (x *QueryReply) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *QueryReply) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=Operation,proto3" json:"Operation,omitempty"` // "Join", "Leave", "Move", "Query"
	ClientId      int64                  `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,3,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	JoinArgs      *JoinArgs              `protobuf:"bytes,4,opt,name=JoinArgs,proto3" json:"JoinArgs,omitempty"`
	LeaveArgs     *LeaveArgs             `protobuf:"bytes,5,opt,name=LeaveArgs,proto3" json:"LeaveArgs,omitempty"`
	MoveArgs      *MoveArgs              `protobuf:"bytes,6,opt,name=MoveArgs,proto3" json:"MoveArgs,omitempty"`
	QueryArgs     *QueryArgs             `protobuf:"bytes,7,opt,name=QueryArgs,proto3" json:"QueryArgs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_shard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{10}
}

func (x *Op) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Op) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Op) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *Op) GetJoinArgs() *JoinArgs {
	if x != nil {
		return x.JoinArgs
	}
	return nil
}

func (x *Op) GetLeaveArgs() *LeaveArgs {
	if x != nil {
		return x.LeaveArgs
	}
	return nil
}

func (x *Op) GetMoveArgs() *MoveArgs {
	if x != nil {
		return x.MoveArgs
	}
	return nil
}

func (x *Op) GetQueryArgs() *QueryArgs {
	if x != nil {
		return x.QueryArgs
	}
	return nil
}

type SMPersistentState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*Config              `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	SeqCache      map[int64]int64        `protobuf:"bytes,2,rep,name=seqCache,proto3" json:"seqCache,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMPersistentState) Reset() {
	*x = SMPersistentState{}
	mi := &file_shard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMPersistentState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMPersistentState) ProtoMessage() {}

func (x *SMPersistentState) ProtoReflect() protoreflect.Message {
	mi := &file_shard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMPersistentState.ProtoReflect.Descriptor instead.
func (*SMPersistentState) Descriptor() ([]byte, []int) {
	return file_shard_proto_rawDescGZIP(), []int{11}
}

func (x *SMPersistentState) GetConfigs() []*Config {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *SMPersistentState) GetSeqCache() map[int64]int64 {
	if x != nil {
		return x.SeqCache
	}
	return nil
}

var File_shard_proto protoreflect.FileDescriptor

const file_shard_proto_rawDesc = "" +
	"\n" +
	"\vshard.proto\x12\x05shard\"\x8b\x02\n" +
	"\x06Config\x12\x10\n" +
	"\x03Num\x18\x01 \x01(\x03R\x03Num\x121\n" +
	"\x06Shards\x18\x02 \x03(\v2\x19.shard.Config.ShardsEntryR\x06Shards\x121\n" +
	"\x06Groups\x18\x03 \x03(\v2\x19.shard.Config.GroupsEntryR\x06Groups\x1a9\n" +
	"\vShardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aN\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.shard.GroupServersR\x05value:\x028\x01\"(\n" +
	"\fGroupServers\x12\x18\n" +
	"\aServers\x18\x01 \x03(\tR\aServers\"\xc5\x01\n" +
	"\bJoinArgs\x126\n" +
	"\aServers\x18\x01 \x03(\v2\x1c.shard.JoinArgs.ServersEntryR\aServers\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x03 \x01(\x03R\x05SeqId\x1aO\n" +
	"\fServersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.shard.GroupServersR\x05value:\x028\x01\"?\n" +
	"\tJoinReply\x12 \n" +
	"\vWrongLeader\x18\x01 \x01(\bR\vWrongLeader\x12\x10\n" +
	"\x03Err\x18\x02 \x01(\tR\x03Err\"Q\n" +
	"\tLeaveArgs\x12\x12\n" +
	"\x04GIDs\x18\x01 \x03(\x03R\x04GIDs\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x03 \x01(\x03R\x05SeqId\"@\n" +
	"\n" +
	"LeaveReply\x12 \n" +
	"\vWrongLeader\x18\x01 \x01(\bR\vWrongLeader\x12\x10\n" +
	"\x03Err\x18\x02 \x01(\tR\x03Err\"d\n" +
	"\bMoveArgs\x12\x14\n" +
	"\x05Shard\x18\x01 \x01(\x03R\x05Shard\x12\x10\n" +
	"\x03GID\x18\x02 \x01(\x03R\x03GID\x12\x1a\n" +
	"\bClientId\x18\x03 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x04 \x01(\x03R\x05SeqId\"?\n" +
	"\tMoveReply\x12 \n" +
	"\vWrongLeader\x18\x01 \x01(\bR\vWrongLeader\x12\x10\n" +
	"\x03Err\x18\x02 \x01(\tR\x03Err\"\x1d\n" +
	"\tQueryArgs\x12\x10\n" +
	"\x03Num\x18\x01 \x01(\x03R\x03Num\"g\n" +
	"\n" +
	"QueryReply\x12 \n" +
	"\vWrongLeader\x18\x01 \x01(\bR\vWrongLeader\x12\x10\n" +
	"\x03Err\x18\x02 \x01(\tR\x03Err\x12%\n" +
	"\x06Config\x18\x03 \x01(\v2\r.shard.ConfigR\x06Config\"\x8e\x02\n" +
	"\x02Op\x12\x1c\n" +
	"\tOperation\x18\x01 \x01(\tR\tOperation\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x03 \x01(\x03R\x05SeqId\x12+\n" +
	"\bJoinArgs\x18\x04 \x01(\v2\x0f.shard.JoinArgsR\bJoinArgs\x12.\n" +
	"\tLeaveArgs\x18\x05 \x01(\v2\x10.shard.LeaveArgsR\tLeaveArgs\x12+\n" +
	"\bMoveArgs\x18\x06 \x01(\v2\x0f.shard.MoveArgsR\bMoveArgs\x12.\n" +
	"\tQueryArgs\x18\a \x01(\v2\x10.shard.QueryArgsR\tQueryArgs\"\xbd\x01\n" +
	"\x11SMPersistentState\x12'\n" +
	"\aconfigs\x18\x01 \x03(\v2\r.shard.ConfigR\aconfigs\x12B\n" +
	"\bseqCache\x18\x02 \x03(\v2&.shard.SMPersistentState.SeqCacheEntryR\bseqCache\x1a;\n" +
	"\rSeqCacheEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012\xbf\x01\n" +
	"\vShardMaster\x12)\n" +
	"\x04Join\x12\x0f.shard.JoinArgs\x1a\x10.shard.JoinReply\x12,\n" +
	"\x05Leave\x12\x10.shard.LeaveArgs\x1a\x11.shard.LeaveReply\x12)\n" +
	"\x04Move\x12\x0f.shard.MoveArgs\x1a\x10.shard.MoveReply\x12,\n" +
	"\x05Query\x12\x10.shard.QueryArgs\x1a\x11.shard.QueryReplyB\vZ\t./shardpbb\x06proto3"

var (
	file_shard_proto_rawDescOnce sync.Once
	file_shard_proto_rawDescData []byte
)

func file_shard_proto_rawDescGZIP() []byte {
	file_shard_proto_rawDescOnce.Do(func() {
		file_shard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shard_proto_rawDesc), len(file_shard_proto_rawDesc)))
	})
	return file_shard_proto_rawDescData
}

var file_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_shard_proto_goTypes = []any{
	(*Config)(nil),            // 0: shard.Config
	(*GroupServers)(nil),      // 1: shard.GroupServers
	(*JoinArgs)(nil),          // 2: shard.JoinArgs
	(*JoinReply)(nil),         // 3: shard.JoinReply
	(*LeaveArgs)(nil),         // 4: shard.LeaveArgs
	(*LeaveReply)(nil),        // 5: shard.LeaveReply
	(*MoveArgs)(nil),          // 6: shard.MoveArgs
	(*MoveReply)(nil),         // 7: shard.MoveReply
	(*QueryArgs)(nil),         // 8: shard.QueryArgs
	(*QueryReply)(nil),        // 9: shard.QueryReply
	(*Op)(nil),                // 10: shard.Op
	(*SMPersistentState)(nil), // 11: shard.SMPersistentState
	nil,                       // 12: shard.Config.ShardsEntry
	nil,                       // 13: shard.Config.GroupsEntry
	nil,                       // 14: shard.JoinArgs.ServersEntry
	nil,                       // 15: shard.SMPersistentState.SeqCacheEntry
}
var file_shard_proto_depIdxs = []int32{
	12, // 0: shard.Config.Shards:type_name -> shard.Config.ShardsEntry
	13, // 1: shard.Config.Groups:type_name -> shard.Config.GroupsEntry
	14, // 2: shard.JoinArgs.Servers:type_name -> shard.JoinArgs.ServersEntry
	0,  // 3: shard.QueryReply.Config:type_name -> shard.Config
	2,  // 4: shard.Op.JoinArgs:type_name -> shard.JoinArgs
	4,  // 5: shard.Op.LeaveArgs:type_name -> shard.LeaveArgs
	6,  // 6: shard.Op.MoveArgs:type_name -> shard.MoveArgs
	8,  // 7: shard.Op.QueryArgs:type_name -> shard.QueryArgs
	0,  // 8: shard.SMPersistentState.configs:type_name -> shard.Config
	15, // 9: shard.SMPersistentState.seqCache:type_name -> shard.SMPersistentState.SeqCacheEntry
	1,  // 10: shard.Config.GroupsEntry.value:type_name -> shard.GroupServers
	1,  // 11: shard.JoinArgs.ServersEntry.value:type_name -> shard.GroupServers
	2,  // 12: shard.ShardMaster.Join:input_type -> shard.JoinArgs
	4,  // 13: shard.ShardMaster.Leave:input_type -> shard.LeaveArgs
	6,  // 14: shard.ShardMaster.Move:input_type -> shard.MoveArgs
	8,  // 15: shard.ShardMaster.Query:input_type -> shard.QueryArgs
	3,  // 16: shard.ShardMaster.Join:output_type -> shard.JoinReply
	5,  // 17: shard.ShardMaster.Leave:output_type -> shard.LeaveReply
	7,  // 18: shard.ShardMaster.Move:output_type -> shard.MoveReply
	9,  // 19: shard.ShardMaster.Query:output_type -> shard.QueryReply
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_shard_proto_init() }
func file_shard_proto_init() {
	if File_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shard_proto_rawDesc), len(file_shard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shard_proto_goTypes,
		DependencyIndexes: file_shard_proto_depIdxs,
		MessageInfos:      file_shard_proto_msgTypes,
	}.Build()
	File_shard_proto = out.File
	file_shard_proto_goTypes = nil
	file_shard_proto_depIdxs = nil
}
