// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: kvraft.proto

package kvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftKV_Get_FullMethodName            = "/kvraft.RaftKV/Get"
	RaftKV_PutAppend_FullMethodName      = "/kvraft.RaftKV/PutAppend"
	RaftKV_BatchGet_FullMethodName       = "/kvraft.RaftKV/BatchGet"
	RaftKV_Watch_FullMethodName          = "/kvraft.RaftKV/Watch"
	RaftKV_SendAddNode_FullMethodName    = "/kvraft.RaftKV/SendAddNode"
	RaftKV_SendRemoveNode_FullMethodName = "/kvraft.RaftKV/SendRemoveNode"
	RaftKV_FetchShardData_FullMethodName = "/kvraft.RaftKV/FetchShardData"
	RaftKV_GCShardData_FullMethodName    = "/kvraft.RaftKV/GCShardData"
)

// RaftKVClient is the client API for RaftKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftKVClient interface {
	Get(ctx context.Context, in *GetArgs, opts ...grpc.CallOption) (*GetReply, error)
	PutAppend(ctx context.Context, in *PutAppendArgs, opts ...grpc.CallOption) (*PutAppendReply, error)
	BatchGet(ctx context.Context, in *BatchGetArgs, opts ...grpc.CallOption) (*BatchGetReply, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
	SendAddNode(ctx context.Context, in *AddNodeArgs, opts ...grpc.CallOption) (*AddNodeReply, error)
	SendRemoveNode(ctx context.Context, in *RemoveNodeArgs, opts ...grpc.CallOption) (*RemoveNodeReply, error)
	FetchShardData(ctx context.Context, in *FetchShardArgs, opts ...grpc.CallOption) (*FetchShardReply, error)
	// 内部通信接口：通知旧主清理分片数据
	GCShardData(ctx context.Context, in *GCShardArgs, opts ...grpc.CallOption) (*GCShardReply, error)
}

type raftKVClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftKVClient(cc grpc.ClientConnInterface) RaftKVClient {
	return &raftKVClient{cc}
}

func (c *raftKVClient) Get(ctx context.Context, in *GetArgs, opts ...grpc.CallOption) (*GetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReply)
	err := c.cc.Invoke(ctx, RaftKV_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftKVClient) PutAppend(ctx context.Context, in *PutAppendArgs, opts ...grpc.CallOption) (*PutAppendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutAppendReply)
	err := c.cc.Invoke(ctx, RaftKV_PutAppend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftKVClient) BatchGet(ctx context.Context, in *BatchGetArgs, opts ...grpc.CallOption) (*BatchGetReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetReply)
	err := c.cc.Invoke(ctx, RaftKV_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftKVClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftKV_ServiceDesc.Streams[0], RaftKV_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftKV_WatchClient = grpc.ServerStreamingClient[WatchResponse]

func (c *raftKVClient) SendAddNode(ctx context.Context, in *AddNodeArgs, opts ...grpc.CallOption) (*AddNodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNodeReply)
	err := c.cc.Invoke(ctx, RaftKV_SendAddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftKVClient) SendRemoveNode(ctx context.Context, in *RemoveNodeArgs, opts ...grpc.CallOption) (*RemoveNodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveNodeReply)
	err := c.cc.Invoke(ctx, RaftKV_SendRemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftKVClient) FetchShardData(ctx context.Context, in *FetchShardArgs, opts ...grpc.CallOption) (*FetchShardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchShardReply)
	err := c.cc.Invoke(ctx, RaftKV_FetchShardData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftKVClient) GCShardData(ctx context.Context, in *GCShardArgs, opts ...grpc.CallOption) (*GCShardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GCShardReply)
	err := c.cc.Invoke(ctx, RaftKV_GCShardData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftKVServer is the server API for RaftKV service.
// All implementations must embed UnimplementedRaftKVServer
// for forward compatibility.
type RaftKVServer interface {
	Get(context.Context, *GetArgs) (*GetReply, error)
	PutAppend(context.Context, *PutAppendArgs) (*PutAppendReply, error)
	BatchGet(context.Context, *BatchGetArgs) (*BatchGetReply, error)
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	SendAddNode(context.Context, *AddNodeArgs) (*AddNodeReply, error)
	SendRemoveNode(context.Context, *RemoveNodeArgs) (*RemoveNodeReply, error)
	FetchShardData(context.Context, *FetchShardArgs) (*FetchShardReply, error)
	// 内部通信接口：通知旧主清理分片数据
	GCShardData(context.Context, *GCShardArgs) (*GCShardReply, error)
	mustEmbedUnimplementedRaftKVServer()
}

// UnimplementedRaftKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftKVServer struct{}

func (UnimplementedRaftKVServer) Get(context.Context, *GetArgs) (*GetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRaftKVServer) PutAppend(context.Context, *PutAppendArgs) (*PutAppendReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PutAppend not implemented")
}
func (UnimplementedRaftKVServer) BatchGet(context.Context, *BatchGetArgs) (*BatchGetReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedRaftKVServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedRaftKVServer) SendAddNode(context.Context, *AddNodeArgs) (*AddNodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendAddNode not implemented")
}
func (UnimplementedRaftKVServer) SendRemoveNode(context.Context, *RemoveNodeArgs) (*RemoveNodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendRemoveNode not implemented")
}
func (UnimplementedRaftKVServer) FetchShardData(context.Context, *FetchShardArgs) (*FetchShardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchShardData not implemented")
}
func (UnimplementedRaftKVServer) GCShardData(context.Context, *GCShardArgs) (*GCShardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GCShardData not implemented")
}
func (UnimplementedRaftKVServer) mustEmbedUnimplementedRaftKVServer() {}
func (UnimplementedRaftKVServer) testEmbeddedByValue()                {}

// UnsafeRaftKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftKVServer will
// result in compilation errors.
type UnsafeRaftKVServer interface {
	mustEmbedUnimplementedRaftKVServer()
}

func RegisterRaftKVServer(s grpc.ServiceRegistrar, srv RaftKVServer) {
	// If the following call panics, it indicates UnimplementedRaftKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftKV_ServiceDesc, srv)
}

func _RaftKV_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).Get(ctx, req.(*GetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftKV_PutAppend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutAppendArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).PutAppend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_PutAppend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).PutAppend(ctx, req.(*PutAppendArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftKV_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).BatchGet(ctx, req.(*BatchGetArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftKV_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaftKVServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftKV_WatchServer = grpc.ServerStreamingServer[WatchResponse]

func _RaftKV_SendAddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodeArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).SendAddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_SendAddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).SendAddNode(ctx, req.(*AddNodeArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftKV_SendRemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveNodeArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).SendRemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_SendRemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).SendRemoveNode(ctx, req.(*RemoveNodeArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftKV_FetchShardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchShardArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).FetchShardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_FetchShardData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).FetchShardData(ctx, req.(*FetchShardArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftKV_GCShardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCShardArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftKVServer).GCShardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftKV_GCShardData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftKVServer).GCShardData(ctx, req.(*GCShardArgs))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftKV_ServiceDesc is the grpc.ServiceDesc for RaftKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvraft.RaftKV",
	HandlerType: (*RaftKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RaftKV_Get_Handler,
		},
		{
			MethodName: "PutAppend",
			Handler:    _RaftKV_PutAppend_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _RaftKV_BatchGet_Handler,
		},
		{
			MethodName: "SendAddNode",
			Handler:    _RaftKV_SendAddNode_Handler,
		},
		{
			MethodName: "SendRemoveNode",
			Handler:    _RaftKV_SendRemoveNode_Handler,
		},
		{
			MethodName: "FetchShardData",
			Handler:    _RaftKV_FetchShardData_Handler,
		},
		{
			MethodName: "GCShardData",
			Handler:    _RaftKV_GCShardData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _RaftKV_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kvraft.proto",
}
