// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: kvraft.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_ERR_UNKNOWN      Error = 0
	Error_OK               Error = 1
	Error_ERR_NO_KEY       Error = 2
	Error_ERR_VERSION      Error = 3
	Error_ERR_MAYBE        Error = 4
	Error_ERR_WRONG_LEADER Error = 5
	Error_ERR_WRONG_GROUP  Error = 6
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "ERR_UNKNOWN",
		1: "OK",
		2: "ERR_NO_KEY",
		3: "ERR_VERSION",
		4: "ERR_MAYBE",
		5: "ERR_WRONG_LEADER",
		6: "ERR_WRONG_GROUP",
	}
	Error_value = map[string]int32{
		"ERR_UNKNOWN":      0,
		"OK":               1,
		"ERR_NO_KEY":       2,
		"ERR_VERSION":      3,
		"ERR_MAYBE":        4,
		"ERR_WRONG_LEADER": 5,
		"ERR_WRONG_GROUP":  6,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_kvraft_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_kvraft_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{0}
}

type PutAppendArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=Op,proto3" json:"Op,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=clientId,proto3" json:"clientId,omitempty"`
	RequestId     int64                  `protobuf:"varint,5,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendArgs) Reset() {
	*x = PutAppendArgs{}
	mi := &file_kvraft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendArgs) ProtoMessage() {}

func (x *PutAppendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendArgs.ProtoReflect.Descriptor instead.
func (*PutAppendArgs) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{0}
}

func (x *PutAppendArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutAppendArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutAppendArgs) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *PutAppendArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutAppendArgs) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type PutAppendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=kvraft.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendReply) Reset() {
	*x = PutAppendReply{}
	mi := &file_kvraft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendReply) ProtoMessage() {}

func (x *PutAppendReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendReply.ProtoReflect.Descriptor instead.
func (*PutAppendReply) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{1}
}

func (x *PutAppendReply) GetErr() Error {
	if x != nil {
		return x.Err
	}
	return Error_ERR_UNKNOWN
}

type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	RequestId     int64                  `protobuf:"varint,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_kvraft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{2}
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetArgs) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Err           Error                  `protobuf:"varint,3,opt,name=err,proto3,enum=kvraft.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_kvraft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{3}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetReply) GetErr() Error {
	if x != nil {
		return x.Err
	}
	return Error_ERR_UNKNOWN
}

type KVSnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           map[string]string      `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastOperations map[int64]int64        `protobuf:"bytes,2,rep,name=LastOperations,proto3" json:"LastOperations,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KVSnapshot) Reset() {
	*x = KVSnapshot{}
	mi := &file_kvraft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSnapshot) ProtoMessage() {}

func (x *KVSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSnapshot.ProtoReflect.Descriptor instead.
func (*KVSnapshot) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{4}
}

func (x *KVSnapshot) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KVSnapshot) GetLastOperations() map[int64]int64 {
	if x != nil {
		return x.LastOperations
	}
	return nil
}

var File_kvraft_proto protoreflect.FileDescriptor

const file_kvraft_proto_rawDesc = "" +
	"\n" +
	"\fkvraft.proto\x12\x06kvraft\"\x81\x01\n" +
	"\rPutAppendArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x0e\n" +
	"\x02Op\x18\x03 \x01(\tR\x02Op\x12\x1a\n" +
	"\bclientId\x18\x04 \x01(\x03R\bclientId\x12\x1c\n" +
	"\trequestId\x18\x05 \x01(\x03R\trequestId\"1\n" +
	"\x0ePutAppendReply\x12\x1f\n" +
	"\x03err\x18\x01 \x01(\x0e2\r.kvraft.ErrorR\x03err\"U\n" +
	"\aGetArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\x03R\bclientId\x12\x1c\n" +
	"\trequestId\x18\x03 \x01(\x03R\trequestId\"[\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12\x1f\n" +
	"\x03err\x18\x03 \x01(\x0e2\r.kvraft.ErrorR\x03err\"\x8a\x02\n" +
	"\n" +
	"KVSnapshot\x120\n" +
	"\x04Data\x18\x01 \x03(\v2\x1c.kvraft.KVSnapshot.DataEntryR\x04Data\x12N\n" +
	"\x0eLastOperations\x18\x02 \x03(\v2&.kvraft.KVSnapshot.LastOperationsEntryR\x0eLastOperations\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13LastOperationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01*{\n" +
	"\x05Error\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x0e\n" +
	"\n" +
	"ERR_NO_KEY\x10\x02\x12\x0f\n" +
	"\vERR_VERSION\x10\x03\x12\r\n" +
	"\tERR_MAYBE\x10\x04\x12\x14\n" +
	"\x10ERR_WRONG_LEADER\x10\x05\x12\x13\n" +
	"\x0fERR_WRONG_GROUP\x10\x062n\n" +
	"\x06RaftKV\x12(\n" +
	"\x03Get\x12\x0f.kvraft.GetArgs\x1a\x10.kvraft.GetReply\x12:\n" +
	"\tPutAppend\x12\x15.kvraft.PutAppendArgs\x1a\x16.kvraft.PutAppendReplyB\bZ\x06./kvpbb\x06proto3"

var (
	file_kvraft_proto_rawDescOnce sync.Once
	file_kvraft_proto_rawDescData []byte
)

func file_kvraft_proto_rawDescGZIP() []byte {
	file_kvraft_proto_rawDescOnce.Do(func() {
		file_kvraft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvraft_proto_rawDesc), len(file_kvraft_proto_rawDesc)))
	})
	return file_kvraft_proto_rawDescData
}

var file_kvraft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvraft_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kvraft_proto_goTypes = []any{
	(Error)(0),             // 0: kvraft.Error
	(*PutAppendArgs)(nil),  // 1: kvraft.PutAppendArgs
	(*PutAppendReply)(nil), // 2: kvraft.PutAppendReply
	(*GetArgs)(nil),        // 3: kvraft.GetArgs
	(*GetReply)(nil),       // 4: kvraft.GetReply
	(*KVSnapshot)(nil),     // 5: kvraft.KVSnapshot
	nil,                    // 6: kvraft.KVSnapshot.DataEntry
	nil,                    // 7: kvraft.KVSnapshot.LastOperationsEntry
}
var file_kvraft_proto_depIdxs = []int32{
	0, // 0: kvraft.PutAppendReply.err:type_name -> kvraft.Error
	0, // 1: kvraft.GetReply.err:type_name -> kvraft.Error
	6, // 2: kvraft.KVSnapshot.Data:type_name -> kvraft.KVSnapshot.DataEntry
	7, // 3: kvraft.KVSnapshot.LastOperations:type_name -> kvraft.KVSnapshot.LastOperationsEntry
	3, // 4: kvraft.RaftKV.Get:input_type -> kvraft.GetArgs
	1, // 5: kvraft.RaftKV.PutAppend:input_type -> kvraft.PutAppendArgs
	4, // 6: kvraft.RaftKV.Get:output_type -> kvraft.GetReply
	2, // 7: kvraft.RaftKV.PutAppend:output_type -> kvraft.PutAppendReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kvraft_proto_init() }
func file_kvraft_proto_init() {
	if File_kvraft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvraft_proto_rawDesc), len(file_kvraft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvraft_proto_goTypes,
		DependencyIndexes: file_kvraft_proto_depIdxs,
		EnumInfos:         file_kvraft_proto_enumTypes,
		MessageInfos:      file_kvraft_proto_msgTypes,
	}.Build()
	File_kvraft_proto = out.File
	file_kvraft_proto_goTypes = nil
	file_kvraft_proto_depIdxs = nil
}
