// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: kvraft.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_ERR_UNKNOWN      Error = 0
	Error_OK               Error = 1
	Error_ERR_NO_KEY       Error = 2
	Error_ERR_WRONG_LEADER Error = 3
	Error_ERR_TIMEOUT      Error = 4
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "ERR_UNKNOWN",
		1: "OK",
		2: "ERR_NO_KEY",
		3: "ERR_WRONG_LEADER",
		4: "ERR_TIMEOUT",
	}
	Error_value = map[string]int32{
		"ERR_UNKNOWN":      0,
		"OK":               1,
		"ERR_NO_KEY":       2,
		"ERR_WRONG_LEADER": 3,
		"ERR_TIMEOUT":      4,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_kvraft_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_kvraft_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{0}
}

type PutAppendArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=clientId,proto3" json:"clientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,5,opt,name=seqId,proto3" json:"seqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendArgs) Reset() {
	*x = PutAppendArgs{}
	mi := &file_kvraft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendArgs) ProtoMessage() {}

func (x *PutAppendArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendArgs.ProtoReflect.Descriptor instead.
func (*PutAppendArgs) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{0}
}

func (x *PutAppendArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutAppendArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *PutAppendArgs) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *PutAppendArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *PutAppendArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type PutAppendReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           Error                  `protobuf:"varint,1,opt,name=err,proto3,enum=kvraft.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutAppendReply) Reset() {
	*x = PutAppendReply{}
	mi := &file_kvraft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutAppendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutAppendReply) ProtoMessage() {}

func (x *PutAppendReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutAppendReply.ProtoReflect.Descriptor instead.
func (*PutAppendReply) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{1}
}

func (x *PutAppendReply) GetErr() Error {
	if x != nil {
		return x.Err
	}
	return Error_ERR_UNKNOWN
}

type GetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientId      int64                  `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,3,opt,name=seqId,proto3" json:"seqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArgs) Reset() {
	*x = GetArgs{}
	mi := &file_kvraft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArgs) ProtoMessage() {}

func (x *GetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArgs.ProtoReflect.Descriptor instead.
func (*GetArgs) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{2}
}

func (x *GetArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *GetArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Err           Error                  `protobuf:"varint,2,opt,name=err,proto3,enum=kvraft.Error" json:"err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_kvraft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{3}
}

func (x *GetReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetReply) GetErr() Error {
	if x != nil {
		return x.Err
	}
	return Error_ERR_UNKNOWN
}

type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=Operation,proto3" json:"Operation,omitempty"` // "Get", "Put", "Append"
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	ClientId      int64                  `protobuf:"varint,4,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,5,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_kvraft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{4}
}

func (x *Op) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Op) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Op) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Op) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Op) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type BatchGetArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=Keys,proto3" json:"Keys,omitempty"` // 一次查多个 Key
	ClientId      int64                  `protobuf:"varint,2,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	SeqId         int64                  `protobuf:"varint,3,opt,name=SeqId,proto3" json:"SeqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetArgs) Reset() {
	*x = BatchGetArgs{}
	mi := &file_kvraft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetArgs) ProtoMessage() {}

func (x *BatchGetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetArgs.ProtoReflect.Descriptor instead.
func (*BatchGetArgs) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetArgs) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *BatchGetArgs) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *BatchGetArgs) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type BatchGetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key -> Value 映射
	Err           Error                  `protobuf:"varint,2,opt,name=Err,proto3,enum=kvraft.Error" json:"Err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetReply) Reset() {
	*x = BatchGetReply{}
	mi := &file_kvraft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetReply) ProtoMessage() {}

func (x *BatchGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_kvraft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetReply.ProtoReflect.Descriptor instead.
func (*BatchGetReply) Descriptor() ([]byte, []int) {
	return file_kvraft_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetReply) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *BatchGetReply) GetErr() Error {
	if x != nil {
		return x.Err
	}
	return Error_ERR_UNKNOWN
}

var File_kvraft_proto protoreflect.FileDescriptor

const file_kvraft_proto_rawDesc = "" +
	"\n" +
	"\fkvraft.proto\x12\x06kvraft\"y\n" +
	"\rPutAppendArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\x12\x1a\n" +
	"\bclientId\x18\x04 \x01(\x03R\bclientId\x12\x14\n" +
	"\x05seqId\x18\x05 \x01(\x03R\x05seqId\"1\n" +
	"\x0ePutAppendReply\x12\x1f\n" +
	"\x03err\x18\x01 \x01(\x0e2\r.kvraft.ErrorR\x03err\"M\n" +
	"\aGetArgs\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\x03R\bclientId\x12\x14\n" +
	"\x05seqId\x18\x03 \x01(\x03R\x05seqId\"A\n" +
	"\bGetReply\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1f\n" +
	"\x03err\x18\x02 \x01(\x0e2\r.kvraft.ErrorR\x03err\"|\n" +
	"\x02Op\x12\x1c\n" +
	"\tOperation\x18\x01 \x01(\tR\tOperation\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\x12\x1a\n" +
	"\bClientId\x18\x04 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x05 \x01(\x03R\x05SeqId\"T\n" +
	"\fBatchGetArgs\x12\x12\n" +
	"\x04Keys\x18\x01 \x03(\tR\x04Keys\x12\x1a\n" +
	"\bClientId\x18\x02 \x01(\x03R\bClientId\x12\x14\n" +
	"\x05SeqId\x18\x03 \x01(\x03R\x05SeqId\"\xa6\x01\n" +
	"\rBatchGetReply\x129\n" +
	"\x06Values\x18\x01 \x03(\v2!.kvraft.BatchGetReply.ValuesEntryR\x06Values\x12\x1f\n" +
	"\x03Err\x18\x02 \x01(\x0e2\r.kvraft.ErrorR\x03Err\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*W\n" +
	"\x05Error\x12\x0f\n" +
	"\vERR_UNKNOWN\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x0e\n" +
	"\n" +
	"ERR_NO_KEY\x10\x02\x12\x14\n" +
	"\x10ERR_WRONG_LEADER\x10\x03\x12\x0f\n" +
	"\vERR_TIMEOUT\x10\x042\xa7\x01\n" +
	"\x06RaftKV\x12(\n" +
	"\x03Get\x12\x0f.kvraft.GetArgs\x1a\x10.kvraft.GetReply\x12:\n" +
	"\tPutAppend\x12\x15.kvraft.PutAppendArgs\x1a\x16.kvraft.PutAppendReply\x127\n" +
	"\bBatchGet\x12\x14.kvraft.BatchGetArgs\x1a\x15.kvraft.BatchGetReplyB\bZ\x06./kvpbb\x06proto3"

var (
	file_kvraft_proto_rawDescOnce sync.Once
	file_kvraft_proto_rawDescData []byte
)

func file_kvraft_proto_rawDescGZIP() []byte {
	file_kvraft_proto_rawDescOnce.Do(func() {
		file_kvraft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvraft_proto_rawDesc), len(file_kvraft_proto_rawDesc)))
	})
	return file_kvraft_proto_rawDescData
}

var file_kvraft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kvraft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kvraft_proto_goTypes = []any{
	(Error)(0),             // 0: kvraft.Error
	(*PutAppendArgs)(nil),  // 1: kvraft.PutAppendArgs
	(*PutAppendReply)(nil), // 2: kvraft.PutAppendReply
	(*GetArgs)(nil),        // 3: kvraft.GetArgs
	(*GetReply)(nil),       // 4: kvraft.GetReply
	(*Op)(nil),             // 5: kvraft.Op
	(*BatchGetArgs)(nil),   // 6: kvraft.BatchGetArgs
	(*BatchGetReply)(nil),  // 7: kvraft.BatchGetReply
	nil,                    // 8: kvraft.BatchGetReply.ValuesEntry
}
var file_kvraft_proto_depIdxs = []int32{
	0, // 0: kvraft.PutAppendReply.err:type_name -> kvraft.Error
	0, // 1: kvraft.GetReply.err:type_name -> kvraft.Error
	8, // 2: kvraft.BatchGetReply.Values:type_name -> kvraft.BatchGetReply.ValuesEntry
	0, // 3: kvraft.BatchGetReply.Err:type_name -> kvraft.Error
	3, // 4: kvraft.RaftKV.Get:input_type -> kvraft.GetArgs
	1, // 5: kvraft.RaftKV.PutAppend:input_type -> kvraft.PutAppendArgs
	6, // 6: kvraft.RaftKV.BatchGet:input_type -> kvraft.BatchGetArgs
	4, // 7: kvraft.RaftKV.Get:output_type -> kvraft.GetReply
	2, // 8: kvraft.RaftKV.PutAppend:output_type -> kvraft.PutAppendReply
	7, // 9: kvraft.RaftKV.BatchGet:output_type -> kvraft.BatchGetReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_kvraft_proto_init() }
func file_kvraft_proto_init() {
	if File_kvraft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvraft_proto_rawDesc), len(file_kvraft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvraft_proto_goTypes,
		DependencyIndexes: file_kvraft_proto_depIdxs,
		EnumInfos:         file_kvraft_proto_enumTypes,
		MessageInfos:      file_kvraft_proto_msgTypes,
	}.Build()
	File_kvraft_proto = out.File
	file_kvraft_proto_goTypes = nil
	file_kvraft_proto_depIdxs = nil
}
